version: '3.3'

services:
    mongodb:
        image: mongo:latest
        ports:
            - "8765:27017"
        volumes:
            - "./mount/mongo:/data/db"
        environment:
            MONGO_INITDB_ROOT_USERNAME: api
            MONGO_INITDB_ROOT_PASSWORD: supersecure
            MONGO_INITDB_DATABASE: ecommerce
